### ISSUE TITLE
JNI Exception on Android 6/6.1

### ISSUE THREAD

**Issue by Karim-Akra** [MAJigsaw77/extension-androidtools#5]
I've been using extension-androidtools 1.8.0(it says 2.8.0 in haxelib folder for some reason idk) while compiling on widows 11 to Android and it all works fine with any Android version.

I recently updated to git version and i started getting JNI Exception errors and crashs while called SUtil.getPath specifically on Android 6/6.1

I moved the apk into a different phone with android 10 and it works just fine

I tried downgrading android tools and it didn't make any difference

Here some informations you might need:
SUtil.getPath function: 
```
public static function getPath():String
	{
		#if android
		return  Context.getExternalFilesDir(null) + '/';
		#elseif ios
		return LimeSystem.applicationStorageDirectory;
		#end
	}
```
the crash logs (i was getting 2 different crash logs, one happen when a directory in the external storage is missing and the game fails to create it manually and one when i call SUtil.getPath to reach a file in the external storage):

1-
```
JNI Exception

lime/system/JNI.hx (line 280) android/os/Environment.hx (line 50)

backend/SUtil.hx (line 35) backend/Paths.hx (line 492)

backend/Paths.hx (line 242) objects/Alphabet.hx (line 420)

objects/Alphabet.hx (line 348) CA\Haxe Toolkit\haxe\std/cpp/_std/Type.hx

(line 90)

flixel/group/FixGroup.hx (line 372) objects/Alphabet.hx (line 219) objects/Alphabet.hx (line 87) objects/Alphabet.hx (line 39) options/OptionsState.hx (line 83) flixel/FixGame.hx (line 642) flixel/FixGame.hx (line 729)
```
2-
```
JNI Exception

lime/system/JNI.hx (line 280) android/content/Context.hx (line 24)

backend/SUtil.hx (line 36) backend/Paths.hx (line 334)

objects/HealthIcon.hx (line 31) objects/Healthicon.hx (line 15) states/FreeplayState.hx (line 108)

flixel/FlxGame.hx (line 642)

flixel/FlxGame.hx (line 729)

flixel/FlxGame.hx (line 556)

flixel/FlxGame.hx (line 682)

openfl/events/EventDispatcher.hx (line 402) openfl/display/DisplayObject.hx (line 1399)
```

**Comment by MAJigsaw77** [comment]
I can't really help

**Comment by MAJigsaw77** [comment]
It's mostly versions issue

**Comment by MAJigsaw77** [comment]
Probably should be fixed now (I returned some stuff)

**Comment by Karim-Akra** [comment]
It's still the same but i assume getExternalStorageDirectory works fine

Is it possible to get phone sdk version since android 11 and above have issues with external storages accessing?

I'm gonna make sdk versions under 30 use getExternalStorageDirectory and above 30 use getExternalFilesDir and hopefully will fix all these problems...
